[package]
name = "broguelike-rltk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8"
specs = "~0.18"
specs-derive = "~0.4"